---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: app-cronjob
  labels:
    app: app
spec:
  schedule: "0,10,20,30,40,50 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: app
              image: app:latest
              imagePullPolicy: Never
              env:
                - name: GRPC_PARSER_ADDRESS
                  value: "grpc-server-service:50051"
              resources:
                requests:
                  cpu: "50m"
                  memory: "64Mi"
                limits:
                  cpu: "100m"
                  memory: "128Mi"
          restartPolicy: Never
