---
apiVersion: batch/v1
kind: Job
metadata:
  name: app
  labels:
    app: app
spec:
  template:
    spec:
      containers:
        - name: app
          image: app:latest
          imagePullPolicy: Never
          env:
            - name: GRPC_PARSER_ADDRESS
              value: "grpc-server-service:50051"
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      restartPolicy: Never
  backoffLimit: 4
