# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc

from protocols import parser_pb2 as protocols_dot_parser__pb2

GRPC_GENERATED_VERSION = "1.70.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in protocols/parser_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ParserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ParseBookPage = channel.unary_unary(
            "/demo.Parser/ParseBookPage",
            request_serializer=protocols_dot_parser__pb2.Page.SerializeToString,
            response_deserializer=protocols_dot_parser__pb2.BookResult.FromString,
            _registered_method=True,
        )


class ParserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ParseBookPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "ParseBookPage": grpc.unary_unary_rpc_method_handler(
            servicer.ParseBookPage,
            request_deserializer=protocols_dot_parser__pb2.Page.FromString,
            response_serializer=protocols_dot_parser__pb2.BookResult.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "demo.Parser", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("demo.Parser", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class Parser(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ParseBookPage(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/demo.Parser/ParseBookPage",
            protocols_dot_parser__pb2.Page.SerializeToString,
            protocols_dot_parser__pb2.BookResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
